/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "duktape.h"
/* Header for class com_ndk_priyank_ndkexample_MainActivity */

JNIEXPORT jint JNICALL Java_com_ndk_priyank_ndkexample_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jstring JNICALL Java_com_ndk_priyank_ndkexample_MainActivity_message
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif